### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by JetReloader** [Suman84/steam-market-CSGO-profitable-tradeups-predictor#3]
Is it possible to save the info gathered without it finishes all the search and continue afterwards skipping the existing data when you start again?

**Comment by Suman84** [comment]
currently that is not implemented in code, you could edit code and remove names of collection that have been collected from line 123 yourself if you want to start from that point. 
or i will change code including that features in few days.

**Comment by JetReloader** [comment]
Okay thank you for your respond and your work
