### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by JetReloader** [Suman84/steam-market-CSGO-profitable-tradeups-predictor#4]
"
found at setname=x_x and y_y. rarity=milspec no=2 wear=WW
Possible number of outputs= 1 + 3 = 4
Total input(wear same):1.0
Avg value of output: x
Average Gain = x%
"
Sorry idk how to write you directly I have a question how can I understand which input needs to be more in the tradeup how can I understand it?

**Comment by JetReloader** [comment]
Like 2 from x weapın and 8 from y weapon

**Comment by Suman84** [comment]
I assumed both of them to be 5 of each type, but you could mix and max further for more gain/easier time. Definitely double check maths on if youre going to get pridicted output as things like fluctuating market prices can make code show unprofitable tradeups too.
